# Generated by Django 5.2.6 on 2025-09-29 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('In Person', 'In Person'), ('Phone Call', 'Phone Call')], help_text='Type of meeting (In Person, Phone Call).', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of visit location.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of visit location.', max_digits=9, null=True)),
                ('visit_image', models.ImageField(blank=True, help_text='Upload an image related to the visit.', null=True, upload_to='visits/')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Open', help_text='Status of the visit.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='User who made the visit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_made', to=settings.AUTH_USER_MODEL)),
                ('sales', models.ForeignKey(blank=True, help_text='Related sales record (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='sales.sales')),
                ('send_to', models.ForeignKey(blank=True, help_text='User who recieve sales  visit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ['-created_at'],
            },
        ),
    ]
