# Generated by Django 5.2.6 on 2025-10-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_remove_visit_send_to_visit_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='designation',
        ),
    ]
