# Generated by Django 5.2.6 on 2025-10-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
    ]
