# Generated by Django 5.2.6 on 2025-10-06 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_notes'),
        ('sales', '0012_sales_contact_number_sales_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sales_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesitem'),
        ),
    ]
