# Generated by Django 5.2.6 on 2025-10-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_sales_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='sales_item',
        ),
    ]
