# Generated by Django 5.2.6 on 2025-09-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('Owner', 'Owner'), ('Engineer', 'Engineer'), ('Contractor', 'Contractor')], max_length=100)),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('acquisition_stage', models.CharField(choices=[('Prospecting', 'Prospecting'), ('Qualifying', 'Qualifying'), ('Proposal or Negotiation', 'Proposal or Negotiation'), ('Closing', 'Closing'), ('Payment Followup', 'Payment followup')], default='Prospecting', max_length=50)),
                ('client_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated client budget ', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_detail', models.CharField(max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer')),
            ],
        ),
    ]
