# Generated by Django 5.2.6 on 2025-10-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='client_budget',
        ),
    ]
