# Generated by Django 5.2.6 on 2025-10-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_client_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='client_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated client budget in TZS', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='acquisition_stage',
            field=models.CharField(choices=[('Prospecting', 'Prospecting'), ('Qualifying', 'Qualifying'), ('Proposal or Negotiation', 'Proposal or Negotiation'), ('Closing', 'Closing'), ('Payment Followup', 'Payment Followup')], default='Prospecting', max_length=50),
        ),
    ]
