# Generated by Django 5.2.6 on 2025-10-23 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Returned', 'Returned')], default='Pending', max_length=20)),
                ('user_message', models.TextField(blank=True, help_text='Message from the user when submitting verification', null=True)),
                ('supervisor_message', models.TextField(blank=True, help_text='Supervisor feedback or verification note', null=True)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('sent_to', models.ForeignKey(help_text='Supervisor assigned to verify this record', on_delete=django.db.models.deletion.CASCADE, related_name='sales_verifications_assigned', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='User who submitted this record for verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_verifications_submitted', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='User who performed the verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_verifications_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Verification',
                'verbose_name_plural': 'Sales Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesVerificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='saleverification.salesverification')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
