# Generated by Django 5.2.6 on 2025-09-28 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0002_remove_productinterest_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Won Paid', 'Won Paid'), ('Lost', 'Lost')], default='Open', max_length=30)),
                ('item_discussed', models.TextField(blank=True)),
                ('is_order_final', models.BooleanField(default=False)),
                ('reason_lost', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_added', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customers.customer')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customercontact')),
                ('product_interests', models.ManyToManyField(blank=True, related_name='sales', to='products.productinterest')),
            ],
        ),
    ]
