# Generated by Django 5.2.6 on 2025-09-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Won Paid', 'Won Paid'), ('Won Pending Payment', 'Won Pending Payment'), ('Lost', 'Lost')], default='Open', max_length=30),
        ),
    ]
