# Generated by Django 5.2.6 on 2025-09-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='product',
        ),
    ]
