# Generated by Django 5.2.6 on 2025-09-30 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productinterest_created_at_and_more'),
        ('sales', '0004_remove_salesitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
