# Generated by Django 5.2.6 on 2025-09-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='product',
        ),
    ]
