# Generated by Django 5.2.6 on 2025-09-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_salesitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='contract_outcome',
            field=models.CharField(blank=True, choices=[('Won', 'Won'), ('Lost', 'Lost')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='is_payment_collected',
            field=models.CharField(blank=True, choices=[('Yes-Full', 'Yes-Full'), ('Yes-Partial', 'Yes-Partial'), ('No', 'No')], max_length=20, null=True),
        ),
    ]
