# Generated by Django 5.2.6 on 2025-10-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sales_contract_outcome_sales_is_payment_collected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='item_discussed',
        ),
        migrations.AddField(
            model_name='sales',
            name='client_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated client budget ', max_digits=12, null=True),
        ),
    ]
