# Generated by Django 5.2.6 on 2025-10-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_sales_item_discussed_sales_client_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='designation',
        ),
    ]
