# Generated by Django 5.2.6 on 2025-10-05 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_client_budget'),
        ('sales', '0009_remove_sales_company_remove_sales_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customers.customer'),
        ),
    ]
