# Generated by Django 5.2.6 on 2025-10-05 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_created_at_product_updated_at_and_more'),
        ('sales', '0010_sales_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='products.productinterest'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sales'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
