# Generated by Django 5.2.6 on 2025-10-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_created_at_product_updated_at_and_more'),
        ('sales', '0011_salesitem_product_alter_salesitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='client_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='is_order_final',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Won Paid', 'Won Paid'), ('Won Pending Payment', 'Won Pending Payment'), ('Lost', 'Lost')], default='Open', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='products.productinterest'),
        ),
    ]
