# Generated by Django 5.2.6 on 2025-10-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_sales_contact_number_sales_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='company',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='client_budget',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='contract_outcome',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='is_payment_collected',
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Paid', 'Paid'), ('Won', 'Won'), ('Lost', 'Lost')], default='Open', max_length=30, null=True),
        ),
    ]
