# Generated by Django 5.2.6 on 2025-10-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_created_at_product_updated_at_and_more'),
        ('sales', '0013_rename_company_sales_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product_interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='sales', to='products.productinterest'),
        ),
    ]
