# Generated by Django 5.2.6 on 2025-09-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productinterest_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinterest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productinterest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
